.TH dsoda 1 "11 February 2010"
.SH Name
dsoda \- Digital Soda. A simple front-end for the DSO-2250 USB oscilloscope.
.SH Usage
.B dsoda
or
.B dsodafw
.SH Description
.LP
The DSO-2250 is an EZ-USB device which needs to load its firmware before it's
being used. Depending on installation type of dsoda, the firmware can be loaded
either automatically via udev by fxload utility just after plug-in or manually
with dsodafw script which is a simple fxload + dsoda shell wrapper.

.SH Mouse Bindings

.B scroll+
zoom in

.B scroll-
zoom out

.B shift + left button
pan

.B ctrl + scroll
change the x/y ratio

.B left-click
assign first position of current trigger

.B right-click
assign second position of current trigger

As of this version, the cursor information is written to parent console window
(stdout).

.SH Key Bindings
.B c
change cursor source

.B g
switch grid on/off

.B i
switch interpolation mode (lines/points)

.B h
toggle high contrast screen

.B l
adjust line width

.B escape
center the graph, reset zoom, and clear the cursors

Note that the graph window must have focus.

.SH See also
udev, fxload

.PP
.SH Authors
Ondra Havel <ondrah@users.sourceforge.net>

